### ISSUE TITLE
Создание своих типов пользовательских с использованием Bitrix\Main\Usertype\Types\*.

### ISSUE THREAD

**Issue by Juliaaan1** [freezemage0/bitrix.snippets#17]
Решение, описанное в официальной документации Битрикса (через `CUserType*`) объявлено **deprecated** еще с 18.0.800.

Описать создание своих типов пользовательских полей с использованием нового API, основанного на наследовании от `\Bitrix\Main\Usertype\Types\*` и использованием компонентов для отображения.

**Comment by freezemage0** [comment]
Неактуально, ссылка на документацию: https://dev.1c-bitrix.ru/api_d7/bitrix/main/userfield/introduction.php
Закрываю.
