### ISSUE TITLE
Работа со своей сущностью в компоненте crm.entity.editor.

### ISSUE THREAD

**Issue by Juliaaan1** [freezemage0/bitrix.snippets#8]
Описать процесс использования компонента `bitrix:crm.entity.editor` в связке с произвольной сущностью.

- использование `bitrix:crm.entity.editor` в связке с `bitrix:ui.sidepanel.wrapper`;
- отображение своих вкладок (с использованием _lazyload_);
- отображение полей сущности (_предпочтительно_, из `getMap()` соответствующего класса);
- отображение пользовательских полей сущности (через реализованный `getUfId()` соответствующего класса) с поддержкой кастомных типов пользовательских полей;
- обработка сохранения изменений сущности;
- создание пользовательских полей изнутри карточки детального просмотра;
- использование индивидуальных представлений для отделов/групп пользователей/отдельных пользователей.

**Comment by freezemage0** [comment]
@Juliaaan1 
Не хватает ещё пункта "создание пользовательских полей". `bitrix:crm.entity.editor` это тоже умеет.

**Comment by Juliaaan1** [comment]
> @Juliaaan1
> Не хватает ещё пункта "создание пользовательских полей". `bitrix:crm.entity.editor` это тоже умеет.

Добавил, спасибо за напоминание.

**Comment by freezemage0** [comment]
Неактуально с приходом смарт процессов, закрываю.
